.TH ebook2cwgui 1 "APRIL 2011" Linux "User Manuals"
.SH NAME
ebook2cwgui \- Graphical user interface for ebook2cw (text to Morse converter)
.SH SYNOPSIS
.B ebook2cwgui 
.SH DESCRIPTION
.B ebook2cw
ebook2cw is a command line program which converts a plain text ebook to Morse
code audio files. It works on several platforms, including Windows and Linux.

.SH CONFIG FILE

ebook2cwgui uses the same config file as ebook2cw itself. Changes to the file
can be saved by the GUI. ebook2cw.conf can either reside in the CWD or in 
~/.ebook2cw/

.SH AUTHOR
Fabian Kurz, DJ1YFK <mail@fkurz.net>

http://fkurz.net/ham/ebook2cw.html
.SH "SEE ALSO"
.BR ebook2cw (1)
